### ISSUE TITLE
PlatformIO

### ISSUE THREAD

**Issue by ElectronicsArchiver** [yunkai1841/SmartWatch#1]
Consider switching to **[PlatformIO]** so
source code can be sorted and depenencies
can be linked.

[PlatformIO]: https://platformio.org/

Let me know if you choose to do this
and need help configuring it.

**Comment by yunkai1841** [comment]
I just installed PlatformIO. 
Thank you for tell me the tool. 
I am reading the tutorial.

**Comment by ElectronicsArchiver** [comment]
Great, that will allow for better 
refactored code as well~

**Comment by ElectronicsArchiver** [comment]
Btw, what Ultrasonic sensor library did you use?

**Comment by yunkai1841** [comment]
I dont know. I got it from CD in Arduino kit. 
There is no link for any repository...

**Comment by ElectronicsArchiver** [comment]
Well I found a replacement in #3

**Comment by yunkai1841** [comment]
I got it. It works now. 
It seems argument position is different from my library. 

Btw, PlatformIO is the great IDE. It automaticaly import the library!!!
I'm glad to know the tool.

**Comment by ElectronicsArchiver** [comment]
Well, be sure to execute the update command
every time you change something in `platformio.ini`

In VSCode you can run it by pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>
and searching for `PlatformIO: Rebuild Intellisense Index`

If you have run it recently it should of course still be there.
