### ISSUE TITLE
SimpleDHT11

### ISSUE THREAD

**Issue by ElectronicsArchiver** [yunkai1841/SmartWatch#4]
Was the only reason for disabling `SimpleDHT11`

> // DH11 read temperature and humidity
    // dont work maybe out of memory

or did you get rid of it completely?

Is the code still needed?

**Comment by ElectronicsArchiver** [comment]
Also, what temperature sensor are you using?

> double kelvin = log(10000.0 * ((1024.0 / tempReading - 1)));

> kelvin = 1 / (0.001129148 + (0.000234125 + (0.0000000876741 * kelvin * kelvin )) * kelvin );

Where does this formula come from?

**Comment by yunkai1841** [comment]
I am testing `SimpleDHT11`. The code is still needed. 

Temperature sensor is [MF52](http://www.focusens.com/include/sensor-fitting-show.php?id=106). 
Datasheet is in URL. 
The formula is actually from Arduino starter kit CD.

**Comment by ElectronicsArchiver** [comment]
For that matter, could you please tell me 
all the hardware components you are using?

So you use:
- Arduino UNO
- MF52
- SR04
- Display?
- ...

**Comment by ElectronicsArchiver** [comment]
> Temperature sensor is [MF52](http://www.focusens.com/include/sensor-fitting-show.php?id=106).

The page seems to be down at the moment..
